In [3]:
from sklearn.datasets import load_digits

In [14]:
digit = load_digits()

In [15]:
digit.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [16]:
digit.data.shape

(1797, 64)

In [17]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [18]:
digit.target.shape

(1797,)

In [19]:
digit.target_names # which is the output 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(digit.data, digit.target, test_size = 0.3,stratify=digit.target, random_state=1000)

In [24]:
logistic = LogisticRegression()

In [25]:
logistic.fit(X_train,y_train) # training the model 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
logistic.score(digit.data,digit.target) # overall accuracy 

0.9849749582637729

In [27]:
logistic.score(X_train,y_train) # training data accuracy

0.99840891010342081

In [28]:
logistic.score(X_test,y_test) # test data accuracy 

0.95370370370370372

In [29]:
from sklearn.metrics import confusion_matrix 

In [30]:
confusion_matrix(logistic.predict(digit.data),digit.target) # we will get 10*10 matrix because of 10 output classes ie, 0 to 9 digits as ouptu 

array([[176,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 178,   0,   0,   2,   0,   0,   0,   4,   0],
       [  0,   0, 176,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1, 181,   0,   0,   0,   0,   1,   1],
       [  2,   0,   0,   0, 178,   0,   0,   0,   0,   0],
       [  0,   1,   0,   2,   0, 177,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   2, 181,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 178,   0,   1],
       [  0,   3,   0,   0,   0,   1,   0,   0, 169,   2],
       [  0,   0,   0,   0,   0,   2,   0,   1,   0, 176]])

In [31]:
confusion_matrix(logistic.predict(digit.data),digit.target).shape

(10, 10)

In [35]:
from sklearn.metrics import classification_report

In [39]:
creport = classification_report(logistic.predict(digit.data),digit.target)

In [41]:
type(creport)

str

In [42]:
print(creport)

             precision    recall  f1-score   support

          0       0.99      1.00      0.99       176
          1       0.98      0.97      0.97       184
          2       0.99      1.00      1.00       176
          3       0.99      0.98      0.99       184
          4       0.98      0.99      0.99       180
          5       0.97      0.98      0.98       180
          6       1.00      0.98      0.99       184
          7       0.99      0.99      0.99       179
          8       0.97      0.97      0.97       175
          9       0.98      0.98      0.98       179

avg / total       0.98      0.98      0.98      1797

